In [1]:
#pip install torch

  Using cached torch-1.8.1-cp38-cp38-manylinux1_x86_64.whl (804.1 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
#pip install nltk

  Using cached nltk-3.6.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 82 kB 742 kB/s eta 0:00:011
  Using cached tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
  Using cached regex-2021.4.4-cp38-cp38-manylinux2014_x86_64.whl (733 kB)
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Note: you may need to restart the kernel to use updated packages.


In [1]:
import torch.nn as nn
import torch
import torch.nn.utils.rnn as rnn
import statistics
import nltk # 없으시면 설치하세요: pip install nltk
import random
import collections
import time

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
## Dictionary class 선언
class Dictionary(object):
    def __init__(self, dataset, size):
        ## init vocab ##
        self.word2idx = {'<pad>':0, '<sos>': 1, '<eos>': 2, '<unk>': 3} # 사전 
        self.idx2word = ['<pad>', '<sos>', '<eos>', '<unk>'] # inverted dictionary

        self.build_dict(dataset, size)

    def __call__(self, word):
        return self.word2idx.get(word, self.word2idx['<unk>']) # if word does not exist in vocab then return unk idx

    def add_word(self, word):
        if word not in self.word2idx:
            self.idx2word.append(word)
            self.word2idx[word] = len(self.idx2word) - 1
        return self.word2idx[word]

    def build_dict(self, dataset, dict_size):
        ## Practice ##
        """Tokenize a text file."""
        total_words = (word for sent in dataset for word in sent) # store all words into tuple
        word_freq = collections.Counter(total_words)# count the number of each word: ex) ('The': 10000, 'a': 5555, ...)
        vocab = sorted(word_freq.keys(), key=lambda word: (-word_freq[word], word))# sort by frequency
        vocab = vocab[:dict_size] # truncate
        for word in vocab:
            self.add_word(word)

    def __len__(self):
        return len(self.idx2word)


In [4]:
## Brown dataset Preprocessing (NLTK)
def brown_dataset(min=5, max=30):
    nltk.download('brown')

    # get sentences with the length between min and max
    # convert all words into lower-case
    all_seq = [[token.lower() for token in seq] for seq in nltk.corpus.brown.sents() 
               if min <= len(seq) <= max]

    random.shuffle(all_seq) # shuffle
    return all_seq

In [5]:
## Download Brown dataset
dataset = brown_dataset()
print(len(dataset))
## print some part
print(dataset[0])
print(dataset[1])
print(dataset[2])

[nltk_data] Downloading package brown to /home/piai/nltk_data...
[nltk_data]   Package brown is already up-to-date!


43450
['in', 'order', 'to', 'form', 'a', 'new', 'government', 'it', 'must', 'deal', 'with', 'one', 'of', 'the', 'two', 'rival', 'parties', 'which', 'gained', 'strength', '.']
['far', 'from', 'it', '!', '!']
['he', 'could', 'not', 'break', 'in', 'on', 'an', 'armed', 'man', '.']


In [6]:
## Data handler class 선언
class Corpus(object):
    def __init__(self, dataset, device, dict_size=20000, train_ratio=0.97):
        train_size = int(len(dataset) * train_ratio)
        self.device = device
        self.dictionary = Dictionary(dataset, dict_size)
        self.train = dataset[:train_size] # [0 ~ train_size]
        self.valid = dataset[train_size:] # [train_size: len(dataset)]

    def indexing(self, dat):
        # dat = list(list)
        src_idxes = [] # 모델 입력
        tgt_idxes = [] # 모델 정답
        for sent in dat:
            src_idx = [self.dictionary('<sos>')] + [self.dictionary(word) for word in sent]
            tgt_idx = [self.dictionary(word) for word in sent] + [self.dictionary('<eos>')]
            src_idxes.append(torch.tensor(src_idx).type(torch.int64))
            tgt_idxes.append(torch.tensor(tgt_idx).type(torch.int64))

        src_idxes = rnn.pad_sequence(src_idxes, batch_first=True).to(self.device) # shape = [B, L]
        tgt_idxes = rnn.pad_sequence(tgt_idxes, batch_first=True).to(self.device).view(-1) # flatten shape = [B * L]

        return src_idxes, tgt_idxes

    def batch_iter(self, batch_size, isTrain=True):
        dat = self.train if isTrain else self.valid
        if isTrain:
            random.shuffle(dat)

        for i in range(len(dat) // batch_size):
            batch = dat[i * batch_size: (i+1) * batch_size]
            src, tgt = self.indexing(batch)
            yield {'src': src, 'tgt': tgt}

In [7]:
corpus = Corpus(dataset, device)

In [8]:
# Dictionary 확인
for i, (key, val) in enumerate(corpus.dictionary.word2idx.items()):
    print('word:  {:10s} | index: {:5d} '.format(key, val))
    if i == 20:
        break

word:  <pad>      | index:     0 
word:  <sos>      | index:     1 
word:  <eos>      | index:     2 
word:  <unk>      | index:     3 
word:  the        | index:     4 
word:  .          | index:     5 
word:  ,          | index:     6 
word:  of         | index:     7 
word:  and        | index:     8 
word:  to         | index:     9 
word:  a          | index:    10 
word:  in         | index:    11 
word:  was        | index:    12 
word:  he         | index:    13 
word:  is         | index:    14 
word:  ''         | index:    15 
word:  ``         | index:    16 
word:  it         | index:    17 
word:  that       | index:    18 
word:  for        | index:    19 
word:  ;          | index:    20 


In [9]:
## indexing 함수 결과 확인

# case : 단일 문장 입력 시. 
sent = [dataset[1]]
idx_src, idx_tgt = corpus.indexing(sent)

print(sent)
print(idx_src) # <SOS> index로 시작
print(idx_tgt) # <EOS> index로 종료

print('-' * 90)
## case : 복수 문장 입력 시 (batching)
batch = [dataset[0], dataset[1]]
idx_src, idx_tgt = corpus.indexing(batch)

print(batch)
print(idx_src) # 가장 길이가 긴 문장 (dataset[0]) 보다 짧은 문장 (dataset[1]) 의 경우 남는 길이만큼 padding=0 삽입 확인.
print(idx_tgt)

[['far', 'from', 'it', '!', '!']]
tensor([[  1, 233,  36,  17,  62,  62]], device='cuda:0')
tensor([233,  36,  17,  62,  62,   2], device='cuda:0')
------------------------------------------------------------------------------------------
[['in', 'order', 'to', 'form', 'a', 'new', 'government', 'it', 'must', 'deal', 'with', 'one', 'of', 'the', 'two', 'rival', 'parties', 'which', 'gained', 'strength', '.'], ['far', 'from', 'it', '!', '!']]
tensor([[    1,    11,   304,     9,   265,    10,    84,   325,    17,   105,
           700,    22,    42,     7,     4,    87, 11771,  2277,    51,  3010,
           685,     5],
        [    1,   233,    36,    17,    62,    62,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')
tensor([   11,   304,     9,   265,    10,    84,   325,    17,   105,   700,
           22,    42,     7,     4,    87, 11771,  2277,    51,  3010,   685,
            5,     

In [11]:
## RNN Language model 선언

# Define network
class RNNModel(nn.Module):
    def __init__(self, ntoken, hidden_size, nlayers, dropout=0.1):
        super(RNNModel, self).__init__()
        self.drop = nn.Dropout(dropout)
        self.embeddings = nn.Embedding(ntoken, hidden_size, padding_idx=0) # Practice 
        self.rnn = nn.LSTM(hidden_size, hidden_size, nlayers, dropout=dropout, batch_first=True) # Practice 
        
        self.output_layer = nn.Linear(hidden_size, ntoken) # Practice
        self.sm = nn.LogSoftmax(dim=-1) # log확률값

        self.ntoken = ntoken
        self.hidden_size = hidden_size
        self.nlayers = nlayers

        self.init_weights()

    def init_weights(self):
        initrange = 0.1
        self.embeddings.weight.data.uniform_(-initrange, initrange)
        self.output_layer.weight.data.uniform_(-initrange, initrange)
        self.output_layer.bias.data.zero_()

    def forward(self, input, hidden):
        # shape(input) = [Batch, length]
        emb = self.embeddings(input) # emb = (batch, length, dim)
        output, hidden = self.rnn(emb, hidden) # output = (batch. length. dim)
        output = self.drop(output)
        output = self.output_layer(output) # output = (batch, length, vocab_size)
        output = output.view(-1, self.ntoken) # output = (batch * length, vocab_size)

        return self.sm(output), hidden

    def init_hidden(self, bsz):
        weight = next(self.parameters()) # to set init tensor with the same torch.dtype and torch.device
        return (weight.new_zeros(self.nlayers, bsz, self.hidden_size),
                weight.new_zeros(self.nlayers, bsz, self.hidden_size))


In [48]:
# Hyperparameters
batch_size = 16
hidden_size = 256
dropout = 0.2
max_epoch = 40

# build model
ntokens = len(corpus.dictionary)
model = RNNModel(ntokens, hidden_size, 1, dropout).to(device)
isTrain=True # Flag variable

# set loss func and optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.005)
criterion = nn.NLLLoss(ignore_index=0, reduction='mean')

In [49]:
##### Training / Evaluation Parts #######

In [50]:
# accuracy
def cal_acc(scores, target):
    pred = scores.max(-1)[1]
    non_pad = target.ne(0)
    num_correct = pred.eq(target).masked_select(non_pad).sum().item() 
    num_non_pad = non_pad.sum().item()
    return 100 * (num_correct / num_non_pad)

In [51]:
# train func.
def train():
    model.train() # Turn on training mode which enables dropout.
    mean_loss = []
    mean_acc = []
    start_time = time.time()

    for batch in corpus.batch_iter(batch_size):
        hidden = model.init_hidden(batch_size) # zero vectors for init hidden
        target = batch['tgt'] # flattened target 
        optimizer.zero_grad()
        output, hidden = model(batch['src'], hidden) # output = flatten output = [Batch_size * Length, vocab_size]

        # output shape = (batch * length, vocab_size)
        # target shape = (batch * length)   --> (batch * length, vocab_size) 로 one-hot distribtuion으로 내부적으로 변환되어 비교 수행
        loss = criterion(output, target) # compare between vocab_prob and answer_prob(one-hot converted)
        loss.backward()
        optimizer.step()

        mean_loss.append(loss.item())
        mean_acc.append(cal_acc(output, target))

    total_time = time.time() - start_time
    mean_acc = statistics.mean(mean_acc)
    mean_loss = statistics.mean(mean_loss)

    return mean_loss, total_time, mean_acc

In [52]:
# evaluation func.
def evaluate():
    model.eval() # Turn off dropout
    mean_loss = []
    mean_acc = []

    for batch in corpus.batch_iter(batch_size, isTrain=False):
        with torch.no_grad():
            hidden = model.init_hidden(batch_size)
            target = batch['tgt']
            output, hidden = model(batch['src'], hidden)
            loss = criterion(output, target)
            mean_loss.append(loss.item())
            mean_acc.append(cal_acc(output, target))

    mean_acc = statistics.mean(mean_acc)
    mean_loss = statistics.mean(mean_loss)

    return mean_loss, mean_acc

In [53]:
if isTrain: # set False if you don't need to train model
    start_time = time.time()

    for epoch in range(1, max_epoch+1):
        loss, epoch_time, accuracy = train()
        print('epoch {:4d} | times {:3.3f} |  loss: {:3.3f} | accuracy: {:3.2f}'.format(epoch+1, epoch_time, loss, accuracy))

        if epoch % 10 == 0:
            loss, accuracy = evaluate()
            print('=' * 60)
            print('Evaluation | loss: {:3.3f} | accuracy: {:3.2f}'.format(loss, accuracy))
            print('=' * 60)

    with open('model.pt', 'wb') as f:
        print('save model at: ./model.pt')
        torch.save(model, f)

epoch    2 | times 25.607 |  loss: 5.595 | accuracy: 21.29
epoch    3 | times 25.827 |  loss: 5.051 | accuracy: 23.97
epoch    4 | times 25.772 |  loss: 4.738 | accuracy: 25.34
epoch    5 | times 25.564 |  loss: 4.476 | accuracy: 26.39
epoch    6 | times 25.825 |  loss: 4.257 | accuracy: 27.44
epoch    7 | times 25.877 |  loss: 4.082 | accuracy: 28.41
epoch    8 | times 25.949 |  loss: 3.946 | accuracy: 29.35
epoch    9 | times 25.980 |  loss: 3.841 | accuracy: 30.15
epoch   10 | times 25.537 |  loss: 3.758 | accuracy: 30.73
epoch   11 | times 25.042 |  loss: 3.693 | accuracy: 31.27
Evaluation | loss: 6.267 | accuracy: 23.27
epoch   12 | times 24.659 |  loss: 3.640 | accuracy: 31.71
epoch   13 | times 24.214 |  loss: 3.598 | accuracy: 32.08
epoch   14 | times 24.144 |  loss: 3.566 | accuracy: 32.34
epoch   15 | times 25.253 |  loss: 3.540 | accuracy: 32.62
epoch   16 | times 26.265 |  loss: 3.523 | accuracy: 32.70
epoch   17 | times 25.957 |  loss: 3.506 | accuracy: 32.79
epoch   18 | 

In [58]:
def pred_sent_prob(sent):
    import numpy as np # optinal
    model.eval()
    with torch.no_grad():
        # 1. 모델 입력 및 정답 문장에 대한 단어 indexing
        idx_src, idx_tgt = corpus.indexing(sent)
        # 2. initial hidden 생성
        hidden = model.init_hidden(1)
        # 3. LM의 결과(확률분포) 생성
        output, hidden = model(idx_src, hidden)
        # 4. 모델 확률분포로부터 정답 단어의 각 index에 대한 Log 확률 값 추출.        
        sent_prob=0
        target_list=idx_tgt.tolist()
        # 5. log 확률의 합.
        for i in range(len(target_list)):
            sent_prob+=output[i][target_list[i]]
        # 6. 결과 return (return type: float)
        return sent_prob

In [59]:
# load saved model
with open('./model.pt', 'rb') as f:
    print('load model from: ./model.pt')
    model = torch.load(f).to(device)

    print('log prob of [the dog bark .]: {:3.3f}'.format(pred_sent_prob([['the', 'dog', 'bark', '.']])))
    print('log prob of [the cat bark .]: {:3.3f}'.format(pred_sent_prob([['the', 'cat', 'bark', '.']])))

    print('log prob of [boy am a i .]: {:3.3f}'.format(pred_sent_prob([['boy', 'am', 'a', 'i', '.']])))
    print('log prob of [i am a boy .]: {:3.3f}'.format(pred_sent_prob([['i', 'am', 'a', 'boy', '.']])))


load model from: ./model.pt
log prob of [the dog bark .]: -47.994
log prob of [the cat bark .]: -75.439
log prob of [boy am a i .]: -39.136
log prob of [i am a boy .]: -17.779


In [60]:
def pred_next_word(partial_sent, topN=3):
    model.eval()
    with torch.no_grad():
        # 1. 모델 입력 및 정답 문장에 대한 단어 indexing
        idx_src, idx_tgt = corpus.indexing(partial_sent)
        # 2. initial hidden 생성
        hidden = model.init_hidden(len(partial_sent))
        # 3. LM의 결과(확률분포) 생성
        output, hidden = model(idx_src, hidden)
        # 4. topN에 해당하는 다음단어의 word index 추출 (Hint: torch.topk() 활용)
        values, indexs = torch.topk(output[3], k=topN, dim=-1)
        # 5. word index --> word 로 변환
        topN_word_list=[]
        # 6. topN word list 반환 (return type: list)
        for i in indexs.tolist():
            topN_word_list.append(corpus.dictionary.idx2word[i])
           
        return topN_word_list

In [61]:
partial_sent = [['the', 'next', 'word']]
N=3
candidates = pred_next_word(partial_sent, topN=N)

# print 
partial_sent = ' '.join(partial_sent[0])
print('Top {0} next words for a partial sentence [{1}] is: '.format(N, partial_sent))
print('===>', candidates)

Top 3 next words for a partial sentence [the next word] is: 
===> [',', 'of', 'for']
