In [9]:
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

import torch
import sklearn

# Tensor

In [13]:
a=torch.tensor([[1, 2], [3, 4]], dtype=torch.float, requires_grad=True)
a

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [14]:
# detach(), clone() 복사
b=a.detach() # grad를 뺌/메모리를 공유(b가 바뀌면 a도 바뀜)
c=a.clone() # 요소 값만 복사하여 새로운 tensor 생성
b, c

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[1., 2.],
         [3., 4.]], grad_fn=<CloneBackward>))

In [15]:
# detach()는 메모리를 공유(b가 바뀌면 a도 바뀜)
b[0][0]=9
a

tensor([[9., 2.],
        [3., 4.]], requires_grad=True)

In [16]:
# to() : GPU로 보낼때 주로 사용
d=c.to(dtype=torch.int) # float형을 int형으로
d

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

## 참고. tensor error시 check point!

# 텐서의 차원

In [17]:
# 0차원 텐서
x=torch.tensor(2)
x, x.dim(), x.shape

(tensor(2), 0, torch.Size([]))

In [18]:
?torch.rand

In [19]:
# 1차원 텐서
x=torch.rand(2)
x, x.dim(), x.shape

(tensor([0.7600, 0.4573]), 1, torch.Size([2]))

In [20]:
# 2차원 텐서
x=torch.rand(2, 3)
x, x.dim(), x.shape

(tensor([[0.9055, 0.5700, 0.7948],
         [0.2309, 0.9115, 0.4675]]),
 2,
 torch.Size([2, 3]))

In [21]:
# 3차원 텐서
x=torch.rand(3, 2, 5)
x, x.dim(), x.shape

(tensor([[[0.8323, 0.0213, 0.0353, 0.3913, 0.7186],
          [0.1154, 0.5171, 0.7020, 0.9390, 0.3852]],
 
         [[0.4674, 0.3475, 0.2113, 0.9216, 0.8088],
          [0.5617, 0.1809, 0.9862, 0.6633, 0.5439]],
 
         [[0.3146, 0.2527, 0.6791, 0.7068, 0.2697],
          [0.8197, 0.0525, 0.6392, 0.4088, 0.7589]]]),
 3,
 torch.Size([3, 2, 5]))

In [22]:
# 4차원 텐서
x=torch.rand(128, 3, 32, 32) # batch-size, channel, height, width
x, x.dim(), x.shape

(tensor([[[[0.5754, 0.8823, 0.9708,  ..., 0.8217, 0.8559, 0.0295],
           [0.1967, 0.7708, 0.5741,  ..., 0.9327, 0.4526, 0.7278],
           [0.6750, 0.8609, 0.4494,  ..., 0.4391, 0.0227, 0.2900],
           ...,
           [0.5740, 0.8532, 0.9282,  ..., 0.7420, 0.5758, 0.5240],
           [0.1347, 0.6297, 0.4909,  ..., 0.0554, 0.8782, 0.6917],
           [0.4426, 0.5370, 0.3334,  ..., 0.2194, 0.4542, 0.3453]],
 
          [[0.7792, 0.9372, 0.4376,  ..., 0.6042, 0.6619, 0.1562],
           [0.6393, 0.4099, 0.4062,  ..., 0.3801, 0.6701, 0.2452],
           [0.3038, 0.6495, 0.3240,  ..., 0.4722, 0.9791, 0.8015],
           ...,
           [0.9837, 0.7450, 0.6451,  ..., 0.8604, 0.8030, 0.8168],
           [0.6728, 0.7182, 0.0410,  ..., 0.2425, 0.0869, 0.9930],
           [0.1101, 0.5891, 0.1416,  ..., 0.8206, 0.4072, 0.4238]],
 
          [[0.6384, 0.8644, 0.5399,  ..., 0.6527, 0.3221, 0.9819],
           [0.3523, 0.5654, 0.5365,  ..., 0.3725, 0.0994, 0.0890],
           [0.9337, 0.32

# 2. 차원과 Shape 바꾸기

In [36]:
?torch.unsqueeze

In [ ]:
# unsqueeze(input, dim) / dim(int) : the index at which to insert the singleton dim

In [26]:
x=torch.tensor([[1, 1], [1, 1]])
x=torch.unsqueeze(x, 0)
x

tensor([[[1, 1],
         [1, 1]]])

In [27]:
x.dim(), x.shape

(3, torch.Size([1, 2, 2]))

In [28]:
x=torch.tensor([[1, 1], [1, 1]])
x=x.unsqueeze(1)
x, x.dim(), x.shape

(tensor([[[1, 1]],
 
         [[1, 1]]]),
 3,
 torch.Size([2, 1, 2]))

In [29]:
# squeeze() : 차원 size가 1인 차원을 모두 제거
x=x.squeeze()
x, x.ndimension(), x.size()

(tensor([[1, 1],
         [1, 1]]),
 2,
 torch.Size([2, 2]))

In [30]:
x = torch.rand(2, 1, 1, 1, 2)
x = x.squeeze()
x.dim(), x.shape

(2, torch.Size([2, 2]))

In [ ]:
?torch.Tensor.view

In [32]:
# view(shape)
x = torch.tensor([[1, 1], [1, 1]])
x=x.view(4)
x, x.dim(), x.shape

(tensor([1, 1, 1, 1]), 1, torch.Size([4]))

In [33]:
x = x.view(1, 4)
x, x.dim(), x.shape

(tensor([[1, 1, 1, 1]]), 2, torch.Size([1, 4]))

In [34]:
# view 사용 시, element 수와 shape을 잘 맞춰줘야한다.
try:
    x = x.view(3, 1)
except Exception as e:
    print(e)

shape '[3, 1]' is invalid for input of size 4


In [35]:
# reshape()
x = x.reshape(4, 1) # view와 비슷하지만, memory 공유가 보장되지 않는다. contiguous하면 view() 반환 (자세한 내용은 2번째 reference 참고)
x, x.dim(), x.shape

(tensor([[1],
         [1],
         [1],
         [1]]),
 2,
 torch.Size([4, 1]))

In [37]:
?torch.transpose

In [38]:
# transpose(dim0, dim1)

x = torch.rand(16, 32, 32, 3) # batch size, height, width, channel
x = x.transpose(1, 3)
x.shape

torch.Size([16, 3, 32, 32])

In [39]:
x = torch.arange(1, 25).view(2, 3, 4)
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [40]:
x = x.transpose(0, 1)
x, x.shape

(tensor([[[ 1,  2,  3,  4],
          [13, 14, 15, 16]],
 
         [[ 5,  6,  7,  8],
          [17, 18, 19, 20]],
 
         [[ 9, 10, 11, 12],
          [21, 22, 23, 24]]]),
 torch.Size([3, 2, 4]))

In [41]:
# permute()

x = x.permute(1, 0, 2) # 0 -> 1, 1 -> 0, 2 -> 2 으로 차원 변경
x, x.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]),
 torch.Size([2, 3, 4]))