In [1]:
import torch
import torch.nn

In [2]:
vocab = {
    '청년': 0,
    'AI': 1,
    'BIGDATA': 2,
    'NLP': 3,
    '인공지능': 4,
    'embedding': 5,
    '실습': 6
}

In [5]:
dim=10
emb_mtx = torch.nn.Embedding(len(vocab), dim)

print(emb_mtx)
print(emb_mtx.weight)

Embedding(7, 10)
Parameter containing:
tensor([[-7.9789e-01, -8.9500e-01,  1.1466e+00,  3.5470e-01,  7.8239e-01,
         -2.8967e-01, -1.2091e+00, -4.7296e-01, -9.6393e-01, -1.2348e+00],
        [ 4.2061e-01,  2.5723e-01,  8.0762e-01,  6.8009e-01, -1.1639e+00,
          1.3652e+00,  1.5580e+00,  7.0019e-01,  1.4920e-01, -3.0491e+00],
        [-3.8754e-01, -6.4829e-01, -6.2898e-01, -2.0951e+00,  6.1029e-01,
          4.9715e-01, -1.3171e+00, -9.5460e-01, -1.4703e-01, -8.1013e-01],
        [-4.2023e-01,  7.6849e-01, -2.5679e-01, -2.3972e+00,  2.9309e-01,
          1.1330e+00, -1.0201e+00,  1.8088e+00,  9.3282e-01, -2.1259e+00],
        [ 1.0422e+00,  3.7209e-01, -1.1022e+00, -9.0792e-01,  5.4663e-02,
          5.8953e-02,  1.4389e+00, -2.8572e-01, -1.6348e-01,  2.3625e-01],
        [ 4.8876e-01, -1.8269e+00, -2.2030e-01, -1.2067e-01, -1.4604e+00,
         -2.8896e-01,  4.8998e-01,  7.6315e-01,  2.4287e-01,  1.8642e+00],
        [-3.3554e-01, -1.7903e+00,  1.0238e+00,  1.9672e-01, -1.182

In [10]:
## Practice 1 ##

# print word embedding of '청년'
idx = # make index tensor for '청년'
print(idx)
emb_mtx(idx) # feed index tensor to emb_mtx

tensor([0])


tensor([[-0.7979, -0.8950,  1.1466,  0.3547,  0.7824, -0.2897, -1.2091, -0.4730,
         -0.9639, -1.2348]], grad_fn=<EmbeddingBackward>)

In [33]:
## Practice 2 ##

# print word embeddings for a given sentence: "청년 AI BIGDATA"
sent = ['청년', 'AI', 'BIGDATA']
idxs = []
for word in sent:
    idx = # convert word into index
    idxs.append(idx) # append idx to idxs

idxs = # convert index list to tensor
print(idxs, idxs.size())
print('')

emb = # convert idxs into word embedding
print(emb, emb.size())

tensor([0, 1, 2]) torch.Size([3])
tensor([[-0.7979, -0.8950,  1.1466,  0.3547,  0.7824, -0.2897, -1.2091, -0.4730,
         -0.9639, -1.2348],
        [ 0.4206,  0.2572,  0.8076,  0.6801, -1.1639,  1.3652,  1.5580,  0.7002,
          0.1492, -3.0491],
        [-0.3875, -0.6483, -0.6290, -2.0951,  0.6103,  0.4972, -1.3171, -0.9546,
         -0.1470, -0.8101]], grad_fn=<EmbeddingBackward>) torch.Size([3, 10])


In [34]:
## Practice 03 ##
# construct batch level word embeddings: ["청년 AI BIGDATA", "NLP embedding 실습"]
sents = [['청년', 'AI', 'BIGDATA'],
         ['NLP', 'embedding', '실습']]
batch_idxs = []
for sent in sents:
    idxs = []
    for word in sent:
        idx = # convert word into index
        idxs.append(idx)  # append idx to idxs
    batch_idxs.append(idxs) # append idxs to batch idx

batch_idxs = # convert batch idx to tensor
print(batch_idxs, batch_idxs.size()) 
print('')

emb = # convert idxs into word embedding
print(emb, emb.size())

tensor([[0, 1, 2],
        [3, 5, 6]]) torch.Size([2, 3])

tensor([[[-7.9789e-01, -8.9500e-01,  1.1466e+00,  3.5470e-01,  7.8239e-01,
          -2.8967e-01, -1.2091e+00, -4.7296e-01, -9.6393e-01, -1.2348e+00],
         [ 4.2061e-01,  2.5723e-01,  8.0762e-01,  6.8009e-01, -1.1639e+00,
           1.3652e+00,  1.5580e+00,  7.0019e-01,  1.4920e-01, -3.0491e+00],
         [-3.8754e-01, -6.4829e-01, -6.2898e-01, -2.0951e+00,  6.1029e-01,
           4.9715e-01, -1.3171e+00, -9.5460e-01, -1.4703e-01, -8.1013e-01]],

        [[-4.2023e-01,  7.6849e-01, -2.5679e-01, -2.3972e+00,  2.9309e-01,
           1.1330e+00, -1.0201e+00,  1.8088e+00,  9.3282e-01, -2.1259e+00],
         [ 4.8876e-01, -1.8269e+00, -2.2030e-01, -1.2067e-01, -1.4604e+00,
          -2.8896e-01,  4.8998e-01,  7.6315e-01,  2.4287e-01,  1.8642e+00],
         [-3.3554e-01, -1.7903e+00,  1.0238e+00,  1.9672e-01, -1.1829e+00,
           8.8802e-01,  2.5392e-03,  8.4005e-01,  1.5658e+00,  1.0889e+00]]],
       grad_fn=<EmbeddingBackwa